[package]
name = "tttg_forge_optimizer"
version = "0.1.0"
edition = "2021"

[dependencies]
tttg_forge_core = { path = "../tttg_forge_core" }
serde.workspace = true
serde_json.workspace = true
fnv.workspace = true
thiserror.workspace = true

[dev-dependencies]
approx.workspace = true
criterion.workspace = true

[[bench]]
name = "optimizer_benches"
harness = false
