import type { PlayerInputCategory, PlayerInputFieldSpec } from '../types';

export const PLAYER_INPUT_CATEGORIES = [
  'damage',
  'build',
  'hero',
  'equipment',
  'tech',
  'pet',
  'collectible',
  'lme',
  'ecosystem',
] as const satisfies readonly PlayerInputCategory[];

export const PLAYER_INPUT_FIELD_SPECS = [
  { category: 'damage', key: 'damage.combat_mode', label: 'Mode', input_type: 'select', range: null, default_value: 'lme', source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.enemy_type', label: 'Enemy type', input_type: 'select', range: null, default_value: 'normal', source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.base_attack', label: 'Base attack', input_type: 'number', range: [0, 100000000], default_value: 1000, source_citation: 'from_codex.md:Sprint-B' },
  { category: 'damage', key: 'damage.final_attack', label: 'Final attack', input_type: 'number', range: [0, 100000000], default_value: 0, source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.crit_rate_percent', label: 'Crit Rate', input_type: 'number', range: [0, 1000], default_value: 0, source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.crit_damage_percent', label: 'Crit Damage', input_type: 'number', range: [0, 5000], default_value: 0, source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.damage_percent', label: 'Damage', input_type: 'number', range: [0, 5000], default_value: 0, source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.damage_when_100_up_percent', label: 'Damage at 100 percent up', input_type: 'number', range: [0, 5000], default_value: 0, source_citation: 'from_codex.md:Sprint-B' },
  { category: 'damage', key: 'damage.skill_damage_percent', label: 'Skill Damage', input_type: 'number', range: [0, 5000], default_value: 0, source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.boss_damage_percent', label: 'Boss Damage', input_type: 'number', range: [0, 5000], default_value: 0, source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.elite_damage_percent', label: 'Elite Damage', input_type: 'number', range: [0, 5000], default_value: 0, source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.vulnerability_percent', label: 'Vulnerability', input_type: 'number', range: [0, 5000], default_value: 0, source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.ee_skill_buff_level', label: 'EE skill buff level', input_type: 'number', range: [0, 10], default_value: 0, source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.ee_tailshot_buff_stacks', label: 'EE tailshot stacks', input_type: 'number', range: [0, 20], default_value: 0, source_citation: 'from_dr.md:2.1' },
  { category: 'damage', key: 'damage.ee_tailshot_enabled', label: 'EE tailshot enabled', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.1' },

  { category: 'build', key: 'build.relic_cores_owned', label: 'Relic cores owned', input_type: 'number', range: [0, 999], default_value: 0, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.chaos_cores_owned', label: 'Chaos cores owned', input_type: 'number', range: [0, 999], default_value: 0, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.max_weapon_af', label: 'Weapon max AF', input_type: 'number', range: [0, 5], default_value: 5, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.max_armor_af', label: 'Armor max AF', input_type: 'number', range: [0, 5], default_value: 5, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.max_necklace_af', label: 'Necklace max AF', input_type: 'number', range: [0, 5], default_value: 5, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.max_belt_af', label: 'Belt max AF', input_type: 'number', range: [0, 5], default_value: 5, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.max_gloves_af', label: 'Gloves max AF', input_type: 'number', range: [0, 5], default_value: 5, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.max_boots_af', label: 'Boots max AF', input_type: 'number', range: [0, 5], default_value: 5, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.lock_weapon', label: 'Lock weapon', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.lock_armor', label: 'Lock armor', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.lock_necklace', label: 'Lock necklace', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.lock_belt', label: 'Lock belt', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.lock_gloves', label: 'Lock gloves', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.2' },
  { category: 'build', key: 'build.lock_boots', label: 'Lock boots', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.2' },

  { category: 'hero', key: 'hero.selected_hero_id', label: 'Selected hero', input_type: 'select', range: null, default_value: 'venato', source_citation: 'from_dr.md:2.3' },
  { category: 'hero', key: 'hero.selected_hero_level', label: 'Hero level', input_type: 'number', range: [1, 120], default_value: 1, source_citation: 'from_dr.md:2.3' },
  { category: 'hero', key: 'hero.selected_hero_star', label: 'Hero star', input_type: 'number', range: [0, 8], default_value: 0, source_citation: 'from_dr.md:2.3' },
  { category: 'hero', key: 'hero.selected_hero_awakening', label: 'Hero awakening', input_type: 'number', range: [0, 8], default_value: 0, source_citation: 'from_dr.md:2.3' },
  { category: 'hero', key: 'hero.teamwork_slots_unlocked', label: 'Teamwork slots', input_type: 'number', range: [0, 4], default_value: 0, source_citation: 'from_dr.md:2.3' },
  { category: 'hero', key: 'hero.global_passive_lv40_enabled', label: 'Global passive level 40', input_type: 'checkbox', range: null, default_value: true, source_citation: 'from_dr.md:2.3' },
  { category: 'hero', key: 'hero.global_passive_lv80_enabled', label: 'Global passive level 80', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.3' },
  { category: 'hero', key: 'hero.hero_shards_spent', label: 'Hero shards spent', input_type: 'number', range: [0, 99999], default_value: 0, source_citation: 'from_dr.md:2.3' },
  { category: 'hero', key: 'hero.awakening_cores_spent', label: 'Awakening cores spent', input_type: 'number', range: [0, 99999], default_value: 0, source_citation: 'from_dr.md:2.3' },
  { category: 'hero', key: 'hero.passive_crit_rate_percent', label: 'Passive crit rate', input_type: 'number', range: [0, 500], default_value: 0, source_citation: 'from_dr.md:2.3' },

  { category: 'equipment', key: 'equipment.weapon.item_id', label: 'Weapon item', input_type: 'select', range: null, default_value: 'twinLance', source_citation: 'reference_catalog.md:76' },
  { category: 'equipment', key: 'equipment.weapon.item_level', label: 'Weapon level', input_type: 'number', range: [0, 200], default_value: 1, source_citation: 'from_dr.md:2.4' },
  { category: 'equipment', key: 'equipment.weapon.astral_forge_eaf_level', label: 'Weapon EAF', input_type: 'number', range: [0, 5], default_value: 1, source_citation: 'from_dr.md:2.4' },
  { category: 'equipment', key: 'equipment.weapon.astral_forge_vaf_level', label: 'Weapon VAF', input_type: 'number', range: [0, 5], default_value: 1, source_citation: 'from_dr.md:2.4' },
  { category: 'equipment', key: 'equipment.armor.item_id', label: 'Armor item', input_type: 'select', range: null, default_value: 'evervoidArmor', source_citation: 'reference_catalog.md:71' },
  { category: 'equipment', key: 'equipment.necklace.item_id', label: 'Necklace item', input_type: 'select', range: null, default_value: 'judgmentNecklace', source_citation: 'reference_catalog.md:73' },
  { category: 'equipment', key: 'equipment.belt.item_id', label: 'Belt item', input_type: 'select', range: null, default_value: 'stardustSash', source_citation: 'reference_catalog.md:75' },
  { category: 'equipment', key: 'equipment.gloves.item_id', label: 'Gloves item', input_type: 'select', range: null, default_value: 'moonscarBracer', source_citation: 'reference_catalog.md:74' },
  { category: 'equipment', key: 'equipment.boots.item_id', label: 'Boots item', input_type: 'select', range: null, default_value: 'glacialWarboots', source_citation: 'reference_catalog.md:72' },
  { category: 'equipment', key: 'equipment.necklace.chaos_fusion_level', label: 'Necklace chaos fusion', input_type: 'number', range: [0, 10], default_value: 0, source_citation: 'from_dr.md:2.4' },
  { category: 'equipment', key: 'equipment.weapon.xeno_transmute_level', label: 'Weapon xeno transmute', input_type: 'number', range: [0, 13], default_value: 0, source_citation: 'from_dr.md:2.4' },
  { category: 'equipment', key: 'equipment.weapon.designs_owned', label: 'Weapon designs owned', input_type: 'number', range: [0, 999999], default_value: 0, source_citation: 'from_dr.md:2.4' },

  { category: 'tech', key: 'tech.selected_attack_parts', label: 'Attack tech parts', input_type: 'select', range: null, default_value: '', source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.selected_defense_parts', label: 'Defense tech parts', input_type: 'select', range: null, default_value: '', source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.resonance_level', label: 'Resonance level', input_type: 'number', range: [0, 999], default_value: 0, source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.resonance_atk_percent', label: 'Resonance ATK percent', input_type: 'number', range: [0, 5000], default_value: 0, source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.chips_available', label: 'Chips available', input_type: 'number', range: [0, 999], default_value: 0, source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.twinborn_enabled', label: 'Twinborn enabled', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.twinborn_main_part_id', label: 'Twinborn main part', input_type: 'select', range: null, default_value: 'drone', source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.twinborn_support_part_id', label: 'Twinborn support part', input_type: 'select', range: null, default_value: 'forcefield', source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.drone_chip_percent', label: 'Drone chip percent', input_type: 'number', range: [0, 100], default_value: 0, source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.forcefield_chip_percent', label: 'Forcefield chip percent', input_type: 'number', range: [0, 100], default_value: 0, source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.soccer_chip_percent', label: 'Soccer chip percent', input_type: 'number', range: [0, 100], default_value: 0, source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.durian_chip_percent', label: 'Durian chip percent', input_type: 'number', range: [0, 100], default_value: 0, source_citation: 'from_dr.md:2.5' },
  { category: 'tech', key: 'tech.auto_assign_mode', label: 'Auto assign mode', input_type: 'select', range: null, default_value: 'lme', source_citation: 'from_dr.md:2.5' },

  { category: 'pet', key: 'pet.deployed_pet_id', label: 'Deployed pet', input_type: 'select', range: null, default_value: 'rex', source_citation: 'reference_catalog.md:24' },
  { category: 'pet', key: 'pet.deployed_is_xeno', label: 'Deployed pet is Xeno', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.6' },
  { category: 'pet', key: 'pet.awakening_level', label: 'Pet awakening', input_type: 'number', range: [0, 8], default_value: 0, source_citation: 'from_dr.md:2.6' },
  { category: 'pet', key: 'pet.resonance_chance', label: 'Pet resonance chance', input_type: 'number', range: [0, 100], default_value: 0, source_citation: 'from_dr.md:2.6' },
  { category: 'pet', key: 'pet.resonance_atk', label: 'Pet resonance ATK', input_type: 'number', range: [0, 999999], default_value: 0, source_citation: 'from_dr.md:2.6' },
  { category: 'pet', key: 'pet.assist_pet_1_id', label: 'Assist pet 1', input_type: 'select', range: null, default_value: '', source_citation: 'from_dr.md:2.6' },
  { category: 'pet', key: 'pet.assist_pet_2_id', label: 'Assist pet 2', input_type: 'select', range: null, default_value: '', source_citation: 'from_dr.md:2.6' },
  { category: 'pet', key: 'pet.assist_skill_filter_enabled', label: 'Assist filter enabled', input_type: 'checkbox', range: null, default_value: true, source_citation: 'from_dr.md:2.6' },
  { category: 'pet', key: 'pet.xeno_preview_enabled', label: 'Xeno preview enabled', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.6' },

  { category: 'collectible', key: 'collectible.edition_progress', label: 'Set progress', input_type: 'number', range: [0, 38], default_value: 38, source_citation: 'reference_catalog.md:334' },
  { category: 'collectible', key: 'collectible.red_star_total', label: 'Red star total', input_type: 'number', range: [0, 999], default_value: 0, source_citation: 'from_dr.md:2.7' },
  { category: 'collectible', key: 'collectible.yellow_star_total', label: 'Yellow star total', input_type: 'number', range: [0, 999], default_value: 0, source_citation: 'from_dr.md:2.7' },
  { category: 'collectible', key: 'collectible.custom_collection_slots', label: 'Custom collection slots', input_type: 'number', range: [0, 99], default_value: 2, source_citation: 'from_dr.md:2.7' },
  { category: 'collectible', key: 'collectible.advanced_collector_heart_level', label: 'Advanced collector heart', input_type: 'number', range: [0, 10], default_value: 0, source_citation: 'from_dr.md:2.7' },
  { category: 'collectible', key: 'collectible.aim_indicator_enabled', label: 'Aim indicator enabled', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.7' },
  { category: 'collectible', key: 'collectible.target_collectible_id', label: 'Target collectible', input_type: 'text', range: null, default_value: '', source_citation: 'from_dr.md:2.7' },
  { category: 'collectible', key: 'collectible.equipment_skill_buff_enabled', label: 'Equipment skill buff enabled', input_type: 'checkbox', range: null, default_value: false, source_citation: 'from_dr.md:2.7' },

  { category: 'lme', key: 'lme.battle_phase', label: 'LME phase', input_type: 'select', range: null, default_value: 'battle', source_citation: 'from_dr.md:2.8' },
  { category: 'lme', key: 'lme.player_medals', label: 'Player medals', input_type: 'number', range: [0, 999], default_value: 0, source_citation: 'from_dr.md:2.8' },
  { category: 'lme', key: 'lme.opponent_medals', label: 'Opponent medals', input_type: 'number', range: [0, 999], default_value: 0, source_citation: 'from_dr.md:2.8' },
  { category: 'lme', key: 'lme.medal_delta_buff_enabled', label: 'Medal delta buff enabled', input_type: 'checkbox', range: null, default_value: true, source_citation: 'from_dr.md:2.8' },
  { category: 'lme', key: 'lme.turf_nodes_enabled', label: 'Turf nodes enabled', input_type: 'number', range: [0, 99], default_value: 0, source_citation: 'from_dr.md:2.8' },
  { category: 'lme', key: 'lme.attack_turf_percent', label: 'Attack turf percent', input_type: 'number', range: [0, 500], default_value: 0, source_citation: 'from_dr.md:2.8' },
  { category: 'lme', key: 'lme.hp_turf_percent', label: 'HP turf percent', input_type: 'number', range: [0, 500], default_value: 0, source_citation: 'from_dr.md:2.8' },
  { category: 'lme', key: 'lme.basic_talent_nodes', label: 'Basic talent nodes', input_type: 'number', range: [0, 999], default_value: 0, source_citation: 'from_dr.md:2.8' },
  { category: 'lme', key: 'lme.clan_bonus_percent', label: 'Clan bonus percent', input_type: 'number', range: [0, 500], default_value: 0, source_citation: 'from_dr.md:2.8' },

  { category: 'ecosystem', key: 'ecosystem.share_code', label: 'Share code', input_type: 'text', range: null, default_value: '', source_citation: 'from_dr.md:2.9' },
  { category: 'ecosystem', key: 'ecosystem.import_url', label: 'Import URL', input_type: 'text', range: null, default_value: '', source_citation: 'from_dr.md:2.9' },
  { category: 'ecosystem', key: 'ecosystem.locale', label: 'Locale', input_type: 'select', range: null, default_value: 'en', source_citation: 'from_dr.md:2.9' },
  { category: 'ecosystem', key: 'ecosystem.autosave_enabled', label: 'Autosave enabled', input_type: 'checkbox', range: null, default_value: true, source_citation: 'from_dr.md:2.9' },
  { category: 'ecosystem', key: 'ecosystem.source_build_name', label: 'Source build name', input_type: 'text', range: null, default_value: '', source_citation: 'from_dr.md:2.9' },
] as const satisfies readonly PlayerInputFieldSpec[];
