import {
  COLLECTIBLE_EDITION_SCHEMA_INDEX,
  HERO_SCHEMA_INDEX,
  INITIAL_SS_EQUIPMENT,
  LME_TURF_MATRIX_SCHEMA,
  PET_SCHEMA_INDEX,
  TECH_PART_SCHEMA_INDEX,
  WEAPON_SCHEMA_INDEX,
} from '../schemas';
import type {
  EquipmentSlotInputState,
  PlayerState,
} from '../types';

const defaultEquipmentSlot = (
  item_id: string,
  rarity: EquipmentSlotInputState['rarity'] = 'ss',
): EquipmentSlotInputState => ({
  item_id,
  rarity,
  item_level: 1,
  enhancement_level: 0,
  astral_forge_eaf_level: 1,
  astral_forge_vaf_level: 1,
  chaos_fusion_level: 0,
  xeno_transmute_level: 0,
  designs_owned: 0,
});

export const DEFAULT_SIO_PLAYER_STATE: PlayerState = {
  base_attack: 1000,
  selected_hero: HERO_SCHEMA_INDEX[0],
  ss_equipment: INITIAL_SS_EQUIPMENT,
  weapons: WEAPON_SCHEMA_INDEX,
  tech_parts: TECH_PART_SCHEMA_INDEX,
  pets: PET_SCHEMA_INDEX,
  collectibles: COLLECTIBLE_EDITION_SCHEMA_INDEX,
  lme_turf: LME_TURF_MATRIX_SCHEMA,
  mode: 'lme',
  conditional_state: {
    hp_missing_ratio: 0,
    target_is_boss: false,
    target_is_elite: false,
    target_lacerated: false,
    target_weakened: false,
    kill_count: 0,
    shield_active: false,
    skill_active_window: false,
  },
  xeno_transmute_modifier: null,
  damage: {
    combat_mode: 'lme',
    enemy_type: 'normal',
    base_attack: 1000,
    final_attack: 0,
    crit_rate_percent: 0,
    crit_damage_percent: 0,
    damage_percent: 0,
    damage_when_100_up_percent: 0,
    skill_damage_percent: 0,
    boss_damage_percent: 0,
    elite_damage_percent: 0,
    vulnerability_percent: 0,
    ee_skill_buff_level: 0,
    ee_tailshot_buff_stacks: 0,
    ee_tailshot_enabled: false,
  },
  build: {
    relic_cores_owned: 0,
    chaos_cores_owned: 0,
    max_weapon_af: 5,
    max_armor_af: 5,
    max_necklace_af: 5,
    max_belt_af: 5,
    max_gloves_af: 5,
    max_boots_af: 5,
    lock_weapon: false,
    lock_armor: false,
    lock_necklace: false,
    lock_belt: false,
    lock_gloves: false,
    lock_boots: false,
  },
  hero: {
    selected_hero_id: 'venato',
    selected_hero_level: 1,
    selected_hero_star: 0,
    selected_hero_awakening: 0,
    teamwork_slots_unlocked: 0,
    global_passive_lv40_enabled: true,
    global_passive_lv80_enabled: false,
    hero_shards_spent: 0,
    awakening_cores_spent: 0,
    passive_crit_rate_percent: 0,
  },
  equipment: {
    weapon: defaultEquipmentSlot('twinLance'),
    armor: defaultEquipmentSlot('evervoidArmor'),
    necklace: defaultEquipmentSlot('judgmentNecklace'),
    belt: defaultEquipmentSlot('stardustSash'),
    gloves: defaultEquipmentSlot('moonscarBracer'),
    boots: defaultEquipmentSlot('glacialWarboots'),
  },
  tech: {
    selected_attack_parts: [],
    selected_defense_parts: [],
    resonance_level: 0,
    resonance_atk_percent: 0,
    chips_available: 0,
    twinborn_enabled: false,
    twinborn_main_part_id: 'drone',
    twinborn_support_part_id: 'forcefield',
    drone_chip_percent: 0,
    forcefield_chip_percent: 0,
    soccer_chip_percent: 0,
    durian_chip_percent: 0,
    auto_assign_mode: 'lme',
  },
  pet: {
    deployed_pet_id: 'rex',
    deployed_is_xeno: false,
    awakening_level: 0,
    resonance_chance: 0,
    resonance_atk: 0,
    assist_pet_1_id: '',
    assist_pet_2_id: '',
    assist_skill_filter_enabled: true,
    xeno_preview_enabled: false,
  },
  collectible: {
    edition_progress: 10,
    red_star_total: 0,
    yellow_star_total: 0,
    custom_collection_slots: 2,
    advanced_collector_heart_level: 0,
    aim_indicator_enabled: false,
    target_collectible_id: '',
    equipment_skill_buff_enabled: false,
  },
  lme: {
    battle_phase: 'battle',
    player_medals: 0,
    opponent_medals: 0,
    medal_delta_buff_enabled: true,
    turf_nodes_enabled: 0,
    attack_turf_percent: 0,
    hp_turf_percent: 0,
    basic_talent_nodes: 0,
    clan_bonus_percent: 0,
  },
  ecosystem: {
    share_code: '',
    import_url: '',
    locale: 'en',
    autosave_enabled: true,
    source_build_name: '',
  },
};
