[package]
name = "tttg_forge_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tttg_forge_core = { path = "../tttg_forge_core" }
tttg_forge_optimizer = { path = "../tttg_forge_optimizer" }
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
serde-wasm-bindgen.workspace = true

[features]
default = []
compat-exports = []
main-cli = []
pareto-objective-wasm = []

[dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--strip-debug", "--strip-producers"]
